import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Banner from "./Banner";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense>
          <Banner />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
